# Publish a Python package to PyPi using uv
name: Publish Package on PyPi

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v7
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          # Intentionally disabled to prevent poisoning
          enable-cache: false
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          # Pinned Python version
          python-version-file: ".python-version"
      - name: Build package
        run: uv build
      - name: Publish package
        run: uv publish
